import { PDFDocument, StandardFonts, rgb, PDFPage, PDFFont } from "pdf-lib";
import fs from "fs/promises";
import path from "path";

/**
 * Server-side memo PDF generation.
 *
 * Produces a clean A4 layout with:
 *  - KARU green header band + crest + university line
 *  - Memo metadata block (TO, FROM, REF, DATE, SUBJECT)
 *  - Body paragraphs (HTML stripped to plain text)
 *  - Signature block
 *  - Footer with copyright + page numbers
 *
 * Used by the circulation flow so recipients can receive the memo as a
 * PDF attachment in their inbox without having to log in.
 */

export interface MemoPdfData {
  memoReference: string;
  workflowReference?: string;
  subject: string;
  body: string;
  to: string;
  from: string;
  fromTitle?: string;
  fromDepartment?: string;
  cc?: string;
  date: string;
  approvedByName?: string;
  approvedByTitle?: string;
  approvedAt?: string;
}

const KARU_GREEN = rgb(0x02 / 255, 0x77 / 255, 0x3b / 255);
const KARU_GOLD = rgb(0xdd / 255, 0x9f / 255, 0x42 / 255);
const TEXT_DARK = rgb(0.12, 0.12, 0.13);
const TEXT_MUTED = rgb(0.42, 0.45, 0.5);
const BORDER = rgb(0.9, 0.91, 0.93);

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN_X = 56;
const HEADER_H = 110;
const FOOTER_H = 36;
const BODY_TOP = HEADER_H + 30;
const BODY_BOTTOM = FOOTER_H + 30;

function htmlToPlainText(html: string): string {
  return html
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n\n")
    .replace(/<\/(div|h[1-6]|li)>/gi, "\n")
    .replace(/<li[^>]*>/gi, "  • ")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\r\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function wrapText(
  text: string,
  font: PDFFont,
  size: number,
  maxWidth: number
): string[] {
  const lines: string[] = [];
  for (const paragraph of text.split("\n")) {
    if (paragraph === "") {
      lines.push("");
      continue;
    }
    const words = paragraph.split(/\s+/);
    let current = "";
    for (const word of words) {
      const candidate = current ? `${current} ${word}` : word;
      const w = font.widthOfTextAtSize(candidate, size);
      if (w > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = candidate;
      }
    }
    if (current) lines.push(current);
  }
  return lines;
}

async function loadCrestPng(pdf: PDFDocument): Promise<ReturnType<PDFDocument["embedPng"]> | null> {
  try {
    const p = path.join(process.cwd(), "public", "karu-crest.png");
    const bytes = await fs.readFile(p);
    return await pdf.embedPng(bytes);
  } catch {
    return null;
  }
}

function drawHeader(
  page: PDFPage,
  font: PDFFont,
  fontBold: PDFFont,
  crest: { width: number; height: number; scale: (n: number) => { width: number; height: number } } | null,
  crestRef: Awaited<ReturnType<PDFDocument["embedPng"]>> | null,
) {
  // Green band
  page.drawRectangle({
    x: 0,
    y: PAGE_H - HEADER_H,
    width: PAGE_W,
    height: HEADER_H,
    color: KARU_GREEN,
  });

  // Crest (left)
  if (crestRef && crest) {
    const target = 56;
    const aspect = crest.width / crest.height;
    const w = target;
    const h = target / aspect;
    page.drawImage(crestRef, {
      x: MARGIN_X,
      y: PAGE_H - HEADER_H + (HEADER_H - h) / 2,
      width: w,
      height: h,
    });
  }

  // University name (centered)
  const titleSize = 18;
  const title = "KARATINA UNIVERSITY";
  const titleW = fontBold.widthOfTextAtSize(title, titleSize);
  page.drawText(title, {
    x: (PAGE_W - titleW) / 2,
    y: PAGE_H - 50,
    size: titleSize,
    font: fontBold,
    color: rgb(1, 1, 1),
  });

  const sub = "Office of the Registrar — Academic, Research & Student Affairs";
  const subSize = 9;
  const subW = font.widthOfTextAtSize(sub, subSize);
  page.drawText(sub, {
    x: (PAGE_W - subW) / 2,
    y: PAGE_H - 68,
    size: subSize,
    font,
    color: rgb(0.92, 1, 0.95),
  });

  const addr = "P.O Box 1957-10101, KARATINA  ·  +254 (0)716 135 171  ·  www.karu.ac.ke";
  const addrSize = 8;
  const addrW = font.widthOfTextAtSize(addr, addrSize);
  page.drawText(addr, {
    x: (PAGE_W - addrW) / 2,
    y: PAGE_H - 84,
    size: addrSize,
    font,
    color: rgb(0.85, 0.96, 0.9),
  });

  // Gold accent line under header
  page.drawRectangle({
    x: 0,
    y: PAGE_H - HEADER_H - 3,
    width: PAGE_W,
    height: 3,
    color: KARU_GOLD,
  });
}

function drawFooter(
  page: PDFPage,
  font: PDFFont,
  pageNum: number,
  pageCount: number,
) {
  const year = new Date().getFullYear();
  const text = `© ${year} Karatina University · Generated by EDRMS`;
  const size = 8;
  const w = font.widthOfTextAtSize(text, size);
  page.drawText(text, {
    x: (PAGE_W - w) / 2,
    y: 18,
    size,
    font,
    color: TEXT_MUTED,
  });
  const pageLbl = `Page ${pageNum} of ${pageCount}`;
  const pageW = font.widthOfTextAtSize(pageLbl, size);
  page.drawText(pageLbl, {
    x: PAGE_W - MARGIN_X - pageW,
    y: 18,
    size,
    font,
    color: TEXT_MUTED,
  });
  // Top border line of footer
  page.drawLine({
    start: { x: MARGIN_X, y: 32 },
    end: { x: PAGE_W - MARGIN_X, y: 32 },
    thickness: 0.5,
    color: BORDER,
  });
}

export async function generateMemoPdf(data: MemoPdfData): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const fontItalic = await pdf.embedFont(StandardFonts.HelveticaOblique);

  const crestRef = await loadCrestPng(pdf);
  const crest = crestRef
    ? { width: crestRef.width, height: crestRef.height, scale: crestRef.scale }
    : null;

  const pages: PDFPage[] = [];
  let page = pdf.addPage([PAGE_W, PAGE_H]);
  pages.push(page);

  drawHeader(page, font, fontBold, crest, crestRef);

  let cursorY = PAGE_H - BODY_TOP;
  const contentX = MARGIN_X;
  const contentWidth = PAGE_W - 2 * MARGIN_X;

  const writeLine = (
    text: string,
    f: PDFFont,
    size: number,
    color = TEXT_DARK,
  ) => {
    if (cursorY - size < BODY_BOTTOM) {
      page = pdf.addPage([PAGE_W, PAGE_H]);
      pages.push(page);
      drawHeader(page, font, fontBold, crest, crestRef);
      cursorY = PAGE_H - BODY_TOP;
    }
    page.drawText(text, { x: contentX, y: cursorY, size, font: f, color });
    cursorY -= size + 4;
  };

  const writeWrapped = (
    text: string,
    f: PDFFont,
    size: number,
    color = TEXT_DARK,
    leading = 1.5,
  ) => {
    const lines = wrapText(text, f, size, contentWidth);
    for (const ln of lines) {
      if (cursorY - size < BODY_BOTTOM) {
        page = pdf.addPage([PAGE_W, PAGE_H]);
        pages.push(page);
        drawHeader(page, font, fontBold, crest, crestRef);
        cursorY = PAGE_H - BODY_TOP;
      }
      page.drawText(ln, { x: contentX, y: cursorY, size, font: f, color });
      cursorY -= size * leading;
    }
  };

  // ----- Document title strip -----
  page.drawRectangle({
    x: contentX,
    y: cursorY - 18,
    width: contentWidth,
    height: 26,
    color: rgb(0.95, 0.97, 0.95),
  });
  page.drawText("INTERNAL MEMORANDUM", {
    x: contentX + 12,
    y: cursorY - 12,
    size: 11,
    font: fontBold,
    color: KARU_GREEN,
  });
  cursorY -= 38;

  // ----- Metadata table -----
  const metaRows: { label: string; value: string }[] = [
    { label: "To", value: data.to },
    { label: "From", value: data.fromTitle ? `${data.from} (${data.fromTitle})` : data.from },
    ...(data.fromDepartment ? [{ label: "Department", value: data.fromDepartment }] : []),
    ...(data.cc ? [{ label: "CC", value: data.cc }] : []),
    { label: "Reference", value: data.memoReference },
    ...(data.workflowReference
      ? [{ label: "Workflow", value: data.workflowReference }]
      : []),
    { label: "Date", value: data.date },
    { label: "Subject", value: data.subject },
  ];

  const labelW = 90;
  const valueW = contentWidth - labelW - 8;
  for (const row of metaRows) {
    const valueLines = wrapText(row.value, font, 10, valueW);
    const rowHeight = Math.max(16, valueLines.length * 13 + 4);
    if (cursorY - rowHeight < BODY_BOTTOM) {
      page = pdf.addPage([PAGE_W, PAGE_H]);
      pages.push(page);
      drawHeader(page, font, fontBold, crest, crestRef);
      cursorY = PAGE_H - BODY_TOP;
    }
    page.drawText(row.label.toUpperCase(), {
      x: contentX,
      y: cursorY - 11,
      size: 8,
      font: fontBold,
      color: TEXT_MUTED,
    });
    let valueY = cursorY - 11;
    for (const ln of valueLines) {
      page.drawText(ln, {
        x: contentX + labelW,
        y: valueY,
        size: 10,
        font: row.label === "Subject" ? fontBold : font,
        color: TEXT_DARK,
      });
      valueY -= 13;
    }
    cursorY -= rowHeight;
  }

  // Divider
  cursorY -= 6;
  page.drawLine({
    start: { x: contentX, y: cursorY },
    end: { x: contentX + contentWidth, y: cursorY },
    thickness: 0.5,
    color: BORDER,
  });
  cursorY -= 18;

  // ----- Body -----
  const bodyText = htmlToPlainText(data.body);
  writeWrapped(bodyText, font, 11, TEXT_DARK, 1.5);

  // ----- Signature block -----
  cursorY -= 24;
  writeLine("Yours faithfully,", font, 11);
  cursorY -= 28;
  writeLine(data.from.toUpperCase(), fontBold, 11);
  if (data.fromTitle) writeLine(data.fromTitle, font, 10, TEXT_MUTED);
  if (data.fromDepartment) writeLine(data.fromDepartment, font, 10, TEXT_MUTED);

  // ----- Approval stamp -----
  if (data.approvedByName) {
    cursorY -= 18;
    page.drawRectangle({
      x: contentX,
      y: cursorY - 36,
      width: contentWidth,
      height: 44,
      color: rgb(0.96, 0.99, 0.96),
      borderColor: KARU_GREEN,
      borderWidth: 0.7,
    });
    page.drawText("APPROVED", {
      x: contentX + 12,
      y: cursorY - 14,
      size: 9,
      font: fontBold,
      color: KARU_GREEN,
    });
    page.drawText(data.approvedByName, {
      x: contentX + 12,
      y: cursorY - 26,
      size: 11,
      font: fontBold,
      color: TEXT_DARK,
    });
    if (data.approvedByTitle) {
      page.drawText(data.approvedByTitle, {
        x: contentX + 12,
        y: cursorY - 36,
        size: 9,
        font: fontItalic,
        color: TEXT_MUTED,
      });
    }
    if (data.approvedAt) {
      const lbl = `Approved on ${data.approvedAt}`;
      const lblW = font.widthOfTextAtSize(lbl, 9);
      page.drawText(lbl, {
        x: contentX + contentWidth - lblW - 12,
        y: cursorY - 14,
        size: 9,
        font,
        color: TEXT_MUTED,
      });
    }
    cursorY -= 50;
  }

  // ----- Footer on every page -----
  for (let i = 0; i < pages.length; i++) {
    drawFooter(pages[i], font, i + 1, pages.length);
  }

  return await pdf.save();
}
