/**
 * Retention-disposition worker.
 *
 * Runs once a day at 03:00 Africa/Nairobi. On each tick:
 *   1. Find every Document whose retention has fallen due (legal-hold-free).
 *   2. Group by RetentionSchedule.disposalAction so each draft cert holds
 *      one homogeneous action bundle.
 *   3. Create DRAFT DispositionCertificate(s) keyed to the action.
 *   4. Notify every user holding `records:dispose` (in-app notification).
 *
 * Execution of approved certs is a manual step driven from the admin UI —
 * the worker never destroys or archives anything on its own.
 *
 * DEBUG=1 forces an immediate run (skips the 03:00 gate). Useful in dev.
 */
import type { DisposalAction } from "@prisma/client";

import { db } from "@/lib/db";
import { logger } from "@/lib/logger";
import {
  findDueForDisposition,
  findRecordsOfficers,
  proposeDispositionCertificate,
  type DueDocument,
} from "@/lib/retention-disposition";
import { parseCron, nextFireTime } from "@/lib/cron";

const TZ = "Africa/Nairobi";
const DAILY_CRON = "0 3 * * *"; // 03:00 every day
const DEBUG = process.env.DEBUG === "1";

function msUntilNextRun(now: Date = new Date()): number {
  const parsed = parseCron(DAILY_CRON);
  if (!parsed) return 24 * 60 * 60 * 1000; // pathological fallback
  const next = nextFireTime(parsed, now, TZ);
  return Math.max(0, next.getTime() - now.getTime());
}

function groupByAction(docs: DueDocument[]): Map<DisposalAction, DueDocument[]> {
  const m = new Map<DisposalAction, DueDocument[]>();
  for (const d of docs) {
    const bucket = m.get(d.action) ?? [];
    bucket.push(d);
    m.set(d.action, bucket);
  }
  return m;
}

async function notifyRecordsOfficers(
  certificates: { id: string; certificateNo: string; documentCount: number; action: DisposalAction }[],
): Promise<number> {
  if (certificates.length === 0) return 0;
  const officers = await findRecordsOfficers();
  if (officers.length === 0) {
    logger.warn("retention-disposition-worker: no records officers found");
    return 0;
  }
  let sent = 0;
  for (const officer of officers) {
    for (const cert of certificates) {
      try {
        await db.notification.create({
          data: {
            userId: officer.id,
            type: "DISPOSITION",
            title: `New disposition draft — ${cert.certificateNo}`,
            body: `${cert.documentCount} document(s) flagged for ${cert.action}. Review and approve to proceed.`,
            linkUrl: `/admin/disposition`,
          },
        });
        sent++;
      } catch (err) {
        logger.warn("retention-disposition-worker: failed to notify", {
          userId: officer.id,
          certificateId: cert.id,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }
  }
  return sent;
}

async function tick() {
  const start = Date.now();
  try {
    const due = await findDueForDisposition();
    if (due.length === 0) {
      logger.info("retention-disposition-worker: no documents due", {
        durationMs: Date.now() - start,
      });
      return;
    }

    // Pick an approver-of-record so the non-null DispositionCertificate.
    // approvedById can be populated. Preferred: a records officer; fallback:
    // the first admin. The cert stays DRAFT until a human actually approves
    // it via the admin UI — this id is just the proposer-of-record.
    const officers = await findRecordsOfficers();
    const proposer = officers[0];
    if (!proposer) {
      logger.error(
        "retention-disposition-worker: no records officer / admin available to own draft certificate; aborting",
      );
      return;
    }

    const grouped = groupByAction(due);
    const created: {
      id: string;
      certificateNo: string;
      documentCount: number;
      action: DisposalAction;
    }[] = [];

    for (const [action, docs] of grouped) {
      const ids = docs.map((d) => d.documentId);
      const cert = await proposeDispositionCertificate(ids, proposer.id, {
        action,
        remarks: `Auto-generated by retention worker at ${new Date().toISOString()}. Action: ${action}.`,
      });
      created.push({
        id: cert.id,
        certificateNo: cert.certificateNo,
        documentCount: ids.length,
        action,
      });
    }

    const notified = await notifyRecordsOfficers(created);

    logger.info("retention-disposition-worker: pass complete", {
      durationMs: Date.now() - start,
      dueDocuments: due.length,
      certificatesCreated: created.length,
      certificates: created.map((c) => ({
        certificateNo: c.certificateNo,
        action: c.action,
        documentCount: c.documentCount,
      })),
      notificationsSent: notified,
    });
  } catch (err) {
    logger.error("retention-disposition-worker: pass failed", err);
  }
}

let timer: NodeJS.Timeout | null = null;

function scheduleNext() {
  const wait = msUntilNextRun();
  const nextAt = new Date(Date.now() + wait).toISOString();
  logger.info("retention-disposition-worker: next run scheduled", {
    nextRunAt: nextAt,
    tz: TZ,
    waitMs: wait,
  });
  timer = setTimeout(async () => {
    await tick();
    scheduleNext();
  }, wait);
}

async function main() {
  logger.info("retention-disposition-worker started", {
    tz: TZ,
    schedule: DAILY_CRON,
    debug: DEBUG,
  });
  if (DEBUG) {
    await tick();
  }
  scheduleNext();

  async function shutdown(signal: string) {
    logger.info(`retention-disposition-worker: received ${signal}, shutting down`);
    if (timer) clearTimeout(timer);
    await db.$disconnect();
    process.exit(0);
  }
  process.on("SIGTERM", () => shutdown("SIGTERM"));
  process.on("SIGINT", () => shutdown("SIGINT"));
}

main().catch((err) => {
  logger.error("retention-disposition-worker: fatal startup error", err);
  process.exit(1);
});
